export const SET_BREADCRUMB_STATE = 'SET_BREADCRUMB_STATE';
export const FETCH_KEYWORDS = 'FETCH_KEYWORDS';
export const FETCH_KEYWORD_RESULTS = 'FETCH_KEYWORD_RESULTS';
export const FETCH_KEYWORD_ARTICLES = 'FETCH_KEYWORD_ARTICLES';